sources:
- title: '[http://plink.anyfeeder.com/weixin/The-Intellectual](http://plink.anyfeeder.com/weixin/The-Intellectual)'
  xml_url: https://www.ifeed.cc/discover?q=plink.anyfeeder.com/weixin/The-Intellectual
  html_url: ''
  category_id: 3
  enabled: true
  id: 240
