sources:
- title: caoz的梦呓
  xml_url: https://plink.anyfeeder.com/weixin/caozsay
  html_url: ''
  category_id: 5
  enabled: true
  id: 398
- title: X博士
  xml_url: https://plink.anyfeeder.com/weixin/doctorx666
  html_url: ''
  category_id: 5
  enabled: true
  id: 408
